### ISSUE TITLE
`sessionModels` Maps risks large memory use

### ISSUE THREAD

**Issue by xgp** [opdt/keycloak-cassandra-extension#127]
There are several Maps called `sessionModels` in the providers and adapters. I'm probably missing how these are used, but doesn't this risk large/unconstrained memory use for large numbers of sessions?

E.g. 
- https://github.com/opdt/keycloak-cassandra-extension/blob/main/core/src/main/java/de/arbeitsagentur/opdt/keycloak/cassandra/authSession/CassandraAuthSessionProvider.java#L52
- https://github.com/opdt/keycloak-cassandra-extension/blob/main/core/src/main/java/de/arbeitsagentur/opdt/keycloak/cassandra/authSession/CassandraRootAuthSessionAdapter.java#L53

What is the benefit?

**Comment by opdt** [comment]
Keycloak itself doesn't actively optimize database requests since JPA's first level cache is doing it for them. We minimize read requests with our L1 cache interceptor for repositories and write requests with write-batching, using in-memory store for uncommitted changes which are written only on a transaction commit.
Early load tests clearly showed that both of these measures are not only nice to have but very necessary to limit database (and thus network) calls to a minimum.

Memory usage is no issue for normal use cases (i.e. everything not in the Admin UI) since Keycloak providers are request scoped which means these maps never contain more data than is used in a single request.
If you have a large amount of sessions and try to load them in a single request, it could be an issue but there would be other issues like enormous load times as well. We optimize for normal usage of users logging in/out, calling userinfo etc and not for administration use cases where you might want to load a lot of data at once or filter data dynamically.

**Comment by xgp** [comment]
Thank you for the very complete explanation. It is possible to have such requests when loading the Admin UI, so it's good to know that this is not an intended use case.
